#!/bin/bash

echo "
================================================

Running the mac setup by kengz @ Jan 4 2016
for bug reports, contact [ kengzwl@gmail.com ]
This will take just a few minutes.

================================================
"

echo "
=> Requesting permission upfront"
# Ask for the administrator password upfront
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"
# sudo -v
# Keep-alive: update existing `sudo` time stamp until this script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &


# determine if is Mac OSX, or Linux; then run accordingly
if [ $(uname) == "Darwin" ];
# Mac runs below
then (
	bash ~/mac_setup/setup_macOS;
	);
else (
	bash ~/mac_setup/setup_ubuntu;
	);
fi